// Utf-8 dosyası olarak saklanmazsa okuma hatası vermekte...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
// ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js... ...uzun js...
function uzun() {console.log ("Ben uzun js dosyasıyım!..");}
console.log ("Uzun script nihayet yüklendi");